### ISSUE TITLE
Sorting deletes all entries

### ISSUE THREAD

**Issue by Acid147** [twday/vscode-bibmanager#1]
Sorting the entries of a BibTeX file deletes the contents of the file.

**Comment by Acid147** [comment]
Sure. The problem seems to be the difference between `@book` and `@article`.

This doesn't work:

```
@book{example,
	author = {Authors},
	title = {Example Bib Reference.},
	year = {2018},
	publisher = {Publisher}
}
```

And this does work:

```
@article{example,
	author = {Authors},
	title = {Example Bib Reference.},
	year = {2018},
	publisher = {Publisher}
}
```

But even with the article, it reformats the file as

```
@article{example,
	author={Authors}
,	title={Example Bib Reference.}
,	year={2018}
,	publisher={Publisher}
}
```

**Comment by twday** [comment]
Sorting has been removed for now until I fix the parsing system for the entries.
