### ISSUE TITLE
IntelliSense support?

### ISSUE THREAD

**Issue by m93a** [twday/vscode-bibmanager#2]
The extension should provide some context-aware code completion for entry types. Right now there are no available hints for entry types, even though they are [well documented](http://mirrors.ctan.org/biblio/bibtex/base/btxdoc.pdf).

![obrazek](https://user-images.githubusercontent.com/1671665/68977066-a385e880-07f7-11ea-8c2e-f3a01373eebd.png)

**Comment by twday** [comment]
I will look into adding IntelliSense to the extension

**Comment by twday** [comment]
I've converted the extension to use a language server. There is a PR for it (#8) if you want to take a look before it is published

**Comment by twday** [comment]
Latest version has been published to VS Code Marketplace
